"""
Project 3: ...
- Dataset: ...
- Goal: Building perfect model using pipeline and feature engineering correctly. learning all possible outcomes and reasons to be better at competitions and such workings
"""